apiVersion: v1
kind: Service
metadata:
  name: ibm-mq-four
  namespace: anynamespace
  labels:
    app: ibm-mq-four
    app.kubernetes.io/part-of: ibm-mq-four
spec:
  ports:
    - name: 1414-tcp
      protocol: TCP
      port: 1414
      targetPort: 1414
    - name: 9157-tcp
      protocol: TCP
      port: 9157
      targetPort: 9157
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: ibm-mq-four
  type: ClusterIP
  