version: '3.9'
services:
  nodejs-adaptador-cache:
    image: nodejs-adaptador-cache
    container_name: nodejs-adaptador-cache
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis-cache
    networks:
      - reto-network
    environment:
      PORT: 3000
  
  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - 6379:6379
    networks:
      - reto-network
  
networks:
  reto-network:
    name: reto-spring